spring:
  application:
    name: authentication-server
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            secret: ${GOOGLE_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: Trace
